apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-django
  namespace: team9-ns
spec:
  mode: one
  selector:
    namespaces:
      - team9-ns
    labelSelectors:
      app: django-app
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "3m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-consumer
  namespace: team9-ns
spec:
  mode: fixed
  value: "1"
  selector:
    namespaces:
      - team9-ns
    labelSelectors:
      app: test-execute-consumer
  stressors:
    cpu:
      workers: 1
      load: 90
  duration: "2m"
  scheduler:
    cron: "@every 10m"
