apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-testops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: team9
  
  source:
    repoURL: https://github.com/CSU-ITMO-2025-2/team9-testops.git
    targetRevision: main
    path: argocd/apps
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: team9-ns
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - SyncTimeout=1200
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
